spring:
  application:
    name: flight-app
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
server:
  shutdown: graceful
